-- sử dụng master để tạo điều kiện
use master
-- tạo điều kiện kiểm tra xem có database chưa
if exists(select * from sys.databases where name = 'THCSDL_NHOM1')
begin
	drop database THCSDL_NHOM1
end;
create database THCSDL_NHOM1
go
use [THCSDL_NHOM1]
-- tạo bảng KHACHHANG
create table KHACHHANG
(
	MAKHACHHANG char(6) not null Primary key,
	TENCONGTY nvarchar(50) not null,
	TENGIAODICH nvarchar(50) not null,
	DIACHI nvarchar(90) not null,
	EMAIL varchar(50),
	DIENTHOAI varchar(11),
	FAX varchar(11),
	unique(DIENTHOAI, EMAIL, FAX)
)
-- tạo bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANHANVIEN CHAR(6) PRIMARY KEY NOT NULL,
    HO NVARCHAR(25) NOT NULL,
    TEN NVARCHAR(25) NOT NULL,
    NGAYSINH DATETIME CHECK (NGAYSINH < GETDATE()),
    NGAYLAMVIEC DATETIME CHECK (NGAYLAMVIEC <= GETDATE()),
						CHECK(NGAYSINH <= NGAYLAMVIEC),
    DIACHI NVARCHAR(90) NULL,
    DIENTHOAI VARCHAR(11) UNIQUE,
    LUONGCOBAN MONEY CHECK (LUONGCOBAN > 0),
    PHUCAP MONEY CHECK (PHUCAP >= 0) 
)
-- tạo bảng DONDATHANG
create table DONDATHANG
(
	SOHOADON char(6) primary key,
	MAKHACHHANG char(6) not null,
	MANHANVIEN char(6) not null,
	NGAYDATHANG datetime,
	NGAYGIAOHANG datetime,
	NGAYCHUYENHANG datetime,
	NOIGIAOHANG nvarchar,
	foreign key (MAKHACHHANG) references KhachHang(MAKHACHHANG)
		ON DELETE
			CASCADE
		ON UPDATE
			CASCADE,
	foreign key (MANHANVIEN) references NHANVIEN(MANHANVIEN)
		ON DELETE
			CASCADE
		ON UPDATE
			CASCADE
)
-- tạo bảng LOAIHANG
create table LOAIHANG
(
	MALOAIHANG char(6) primary key,
	TENLOAIHANG nvarchar(10) not null
)
-- Tạo Bảng NHACUNGCAP
CREATE TABLE NHACUNGCAP
(
	MACONGTY	CHAR(6)	PRIMARY KEY NOT NULL,
	TENCONGTY	NVARCHAR(50)	NOT NULL,
	TENGIAODICH	NVARCHAR(50)	NOT NULL,
	DIACHI	VARCHAR(90)	NULL,
	DIEN_THOAI	VARCHAR(11)	UNIQUE NULL,
	FAX	VARCHAR(11)	UNIQUE NULL,
	EMAIL	VARCHAR(50)	UNIQUE NULL
)
-- tạo bảng MATHANG
CREATE TABLE MATHANG (
    MAHANG CHAR(6) PRIMARY KEY,
    TENHANG NVARCHAR(100),
    MACONGTY CHAR(6), 
    MALOAIHANG CHAR(6),              
    SOLUONG INT,              
    DONVITINH NVARCHAR(50),   
    GIAHANG MONEY,
    FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY)
		ON DELETE
			CASCADE
		ON UPDATE
			CASCADE,
    FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
		ON DELETE
			CASCADE
		ON UPDATE
			CASCADE,
);

--Tạo bảng CHITIETDATHANG
CREATE TABLE CHITIETDATHANG
(
	SOHOADON	CHAR(6) NOT NULL
		FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON)
			ON DELETE 
				CASCADE
			ON UPDATE
				CASCADE,
	MAHANG	CHAR(6) NOT NULL
		FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
			ON DELETE 
				CASCADE
			ON UPDATE
				CASCADE,
	PRIMARY KEY(MAHANG,SOHOADON),
	GIABAN	MONEY NULL CHECK(GIABAN>0),
	SOLUONG	INT NULL CHECK(SOLUONG>0),
	MUCGIAMGIA	MONEY NULL CHECK(MUCGIAMGIA>0)
)
-- câu 2:Bổ sung ràng buộc thiết lập giá trị mặc định bằng 1 cho cột SOLUONG  và bằng 0 cho cột MUCGIAMGIA trong bảng CHITIETDATHANG

ALTER TABLE CHITIETDATHANG
	ADD CONSTRAINT DF_CHITIETDATHANG_SOLUONG
		DEFAULT 1 FOR SOLUONG,
	CONSTRAINT DF_CHITIETDATHANG_MUCGIAMGIA
		DEFAULT 0 FOR MUCGIAMGIA
-- Câu 3: kiểm tra ngày giao hàng và ngày chuyển hàng phải sau hoặc bằng với ngày đặt hàng
ALTER TABLE DONDATHANG
	ADD CONSTRAINT CHK_DONDATHANG_NGAYGIAOHANG 
		check(NGAYGIAOHANG >= NGAYDATHANG),
	CONSTRAINT CHK_DONDATHANG_NGAYCHUYENHANG 
		check(NGAYCHUYENHANG >= NGAYDATHANG)
-- Câu 4: Bổ sung ràng buộc cho bảng NHANVIEN để đảm bảo rằng một nhân viên chỉ có thể làm việc trong công ty khi đủ 18 tuổi và không quá 60 tuổi.
ALTER TABLE NHANVIEN
	ADD CONSTRAINT CK_TUOINHANVIEN 
		CHECK (DATEDIFF(YEAR, NGAYSINH, NGAYLAMVIEC) >= 18 AND 
				DATEDIFF(YEAR, NGAYSINH, NGAYLAMVIEC) <= 60);



